#line 1 "src/assembler/gblexer.cpp"

#line 3 "src/assembler/gblexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer gbFlexLexer

#ifdef yyalloc
#define gballoc_ALREADY_DEFINED
#else
#define yyalloc gballoc
#endif

#ifdef yyrealloc
#define gbrealloc_ALREADY_DEFINED
#else
#define yyrealloc gbrealloc
#endif

#ifdef yyfree
#define gbfree_ALREADY_DEFINED
#else
#define yyfree gbfree
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int Lexer::yylex()

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 104
#define YY_END_OF_BUFFER 105
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[253] =
    {   0,
        0,    0,    0,    0,  105,  103,  102,  101,  103,  102,
       93,  103,    3,   83,   84,    2,  103,   91,   91,   91,
        1,   82,   75,   76,   77,   78,   99,   99,   79,   99,
       99,   80,   99,   99,   99,   99,   99,   99,   82,   75,
       76,   77,   78,   79,   99,   99,   80,   99,   99,   99,
       99,   99,   99,   98,  104,   94,  104,  101,    0,   31,
        0,   30,   25,    0,    0,   30,    0,  100,    0,    0,
        0,    0,    0,    0,    0,    0,   91,   92,   91,   91,
        0,   89,   86,   90,   87,    0,   90,   99,   99,   74,
       99,   86,   99,   87,   70,   99,   99,   99,   18,   99,

       71,   62,   99,   61,   65,   99,   72,   64,   38,   32,
        7,   99,   17,   99,   99,   99,   99,   53,   55,   99,
       99,   99,   99,   99,   73,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   18,   99,   71,   99,   65,
       99,   64,   32,    7,   99,   99,   99,   99,   99,   53,
       55,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   98,   97,   96,   95,   27,    0,   24,   29,   28,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   92,
       92,   88,   85,   11,   10,   15,   45,   99,   23,   21,
       14,   20,   99,   66,   99,   19,    0,    9,    8,    4,

       63,   44,   99,   46,   41,   49,   52,   51,   54,   40,
       13,   22,   47,   56,   58,   57,   59,   99,   12,   99,
       16,   99,   99,   99,    0,   99,   41,   52,   54,   99,
       99,   26,   67,   68,   81,   69,   39,   37,    5,   36,
        0,   34,   43,   42,   48,   50,    6,   60,    0,   35,
       33,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    1,    1,    8,    9,
       10,    1,    1,   11,   12,   13,    1,   14,   15,   16,
       16,   16,   16,   16,   16,   16,   16,   17,    1,    1,
        1,    1,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   24,   28,   29,   30,   31,   32,
       24,   33,   34,   35,   36,   24,   37,   38,   39,   40,
        1,   41,    1,    1,   24,    1,   42,   43,   44,   45,

       46,   47,   24,   48,   49,   50,   24,   51,   52,   53,
       54,   55,   24,   56,   57,   58,   59,   24,   60,   61,
       62,   63,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    2,    1,    2,    1,    1,
        1,    1,    1,    3,    3,    3,    1,    3,    3,    3,
        3,    3,    3,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        2,    3,    3,    3,    3,    3,    3,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4
    } ;

static const flex_int16_t yy_base[259] =
    {   0,
        0,    0,   61,   62,  453,  454,  454,  454,  449,   84,
      454,  448,  454,   52,  454,  454,   60,  135,   23,   64,
      454,  183,  218,   62,  100,   61,   65,    0,   78,  420,
       57,  428,  417,   65,   74,  101,  248,  416,  118,  120,
      165,  168,  196,   66,  393,   37,  400,  390,   56,  107,
      116,  231,  389,    0,  454,  454,   58,  454,  403,  454,
      101,  111,  454,  379,  124,  130,  437,  454,  419,  416,
      409,  404,  391,  388,  382,  377,  116,  232,  109,    0,
      236,    0,  454,  160,  454,    0,    0,  166,  169,  195,
        0,    0,  410,    0,  233,  395,  268,  272,  401,  279,

      252,    0,  398,    0,  389,  398,    0,  405,    0,  419,
      198,  391,    0,  387,  389,  386,  177,  125,  236,  384,
      398,  394,  381,  275,    0,  282,  384,  395,  395,  379,
      281,  366,  352,  282,  289,  358,  286,  291,  355,  346,
      355,  361,  399,  224,  348,  344,  346,  343,  256,  274,
      277,  341,  354,  350,  338,  278,  280,  341,  351,  351,
      336,    0,  454,  454,  454,  454,  352,  454,  454,  454,
      328,  373,  359,  358,  357,  356,  354,  353,  352,  323,
      454,  309,    0,  314,  321,    0,    0,  332,  322,    0,
      323,  324,  319,    0,  323,    0,  325,    0,    0,    0,

        0,    0,  332,    0,  330,    0,  336,    0,  335,    0,
        0,    0,    0,    0,    0,    0,    0,  319,    0,  314,
        0,  281,  267,  269,  308,  256,  222,  216,  158,  138,
      104,  454,  454,  454,  454,  454,    0,    0,    0,  454,
      215,  454,    0,    0,    0,    0,    0,    0,  179,  454,
      454,  454,  371,  375,  377,  381,  385,  116
    } ;

static const flex_int16_t yy_def[259] =
    {   0,
      252,    1,  253,  253,  252,  252,  252,  252,  252,  252,
      252,  254,  252,  252,  252,  252,  252,  252,   18,   18,
      252,  255,  255,   23,   23,   23,   23,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,   23,   23,
       23,   23,   23,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  256,  252,  252,  257,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  254,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,   18,   20,
       20,   81,  252,   81,  252,  258,   81,   23,   23,   23,
      255,  255,  255,  255,   23,  255,   23,   23,  255,   23,

       23,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
       23,  255,  255,   23,   23,  255,   23,   23,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  256,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,   81,  258,   23,   23,  255,  255,  255,   23,  255,
       23,   23,  255,  255,  255,  255,  252,  255,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  252,  255,  255,  255,  255,  255,
      255,  252,  252,  252,  252,  252,  255,  255,  255,  252,
      252,  252,  255,  255,  255,  255,  255,  255,  252,  252,
      252,    0,  252,  252,  252,  252,  252,  252
    } ;

static const flex_int16_t yy_nxt[518] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,    6,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   28,   33,
       34,   35,   36,   37,   28,   28,   28,   38,   28,   28,
        6,   39,   40,   41,   42,   43,   27,   44,   45,   46,
       47,   28,   48,   49,   50,   51,   52,   28,   28,   28,
       53,   28,   28,   55,   55,   87,   56,   56,   56,   56,
       69,  164,   70,   77,   77,   77,   71,   80,   80,   97,
       88,   98,   81,  252,   88,   72,  104,   91,  109,  110,
       91,  109,  143,   99,   73,  106,   74,  113,  105,   75,

      114,   57,   57,   59,  115,  107,   81,  141,   76,  116,
      165,  113,   60,   61,  146,   62,  107,  100,  183,   88,
      167,  101,  117,   63,  252,  102,  103,   64,  118,   77,
       77,   77,  169,  119,  120,   60,   65,   88,   66,   88,
      168,  170,  206,   91,  207,   91,   63,   78,   79,   79,
       80,   87,   81,   82,   81,   81,   81,   81,  248,   83,
      147,  149,  131,   95,   90,  148,  150,  171,  133,  252,
      132,  151,  152,  182,  182,  169,   81,   84,   81,   81,
       81,   81,   85,  170,   88,   88,  168,   88,  184,  185,
       91,   91,  247,   91,   91,   86,   88,   88,   88,  246,

       88,   88,   88,   89,   88,   90,  134,   92,  135,  137,
      204,  205,   93,  138,   88,   88,  102,  139,  198,  136,
       91,   91,  250,  199,   88,   88,   88,   88,   88,   88,
       94,   88,   88,   88,  250,   88,   88,   95,   88,   88,
       88,  251,   92,   96,  104,  180,  180,  180,  252,   81,
       81,   81,   88,  208,  251,  209,  140,  245,   91,   88,
       88,   88,   88,   88,   88,   94,  121,  122,  198,  123,
      244,  192,  199,  153,  154,  124,  155,   91,  181,  125,
      126,  156,  127,  128,  129,  125,  157,   88,  158,  159,
      160,   88,  214,   91,  189,  188,  191,   91,   88,  216,

       88,   88,  215,  243,   91,   88,   91,   91,   88,  217,
       88,   91,  204,  227,   91,  206,   91,  228,  208,  214,
      229,  216,  182,  182,  184,  185,  239,  191,  215,  238,
      217,  237,  222,   88,  192,  189,  180,  180,  180,   91,
       88,   88,   88,   88,  240,  248,   91,   91,   91,   91,
      247,  240,  246,  245,  241,  244,  243,  239,  238,  237,
      249,  236,  235,  234,  242,  233,  236,  235,  234,  181,
      242,   54,   54,   54,   54,   67,   67,   67,   67,   91,
       91,  162,  233,  162,  162,  163,  163,  163,  163,  232,
      232,  221,  231,  219,  230,  213,  212,  211,  210,  226,

      202,  201,  200,  225,  196,  224,  194,  223,  190,  187,
      186,  221,  220,  219,  218,  213,  212,  211,  210,  203,
      202,  201,  200,  197,  196,  195,  194,  193,  190,  187,
      186,  179,  178,  177,  176,  175,  174,  173,  172,   68,
      166,  166,  161,  145,  144,  142,  130,  112,  111,  108,
       68,   58,  252,    5,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252
    } ;

static const flex_int16_t yy_chk[518] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,   19,    3,    4,    3,    4,
       14,   57,   14,   17,   17,   17,   14,   20,   20,   24,
       26,   24,   20,   19,   27,   14,   26,   24,   31,   31,
       27,   46,   46,   24,   14,   29,   14,   34,   26,   14,

       34,    3,    4,   10,   35,   29,   20,   44,   14,   35,
       57,   49,   10,   10,   49,   10,   44,   25,  258,   25,
       61,   25,   36,   10,   20,   25,   25,   10,   36,   77,
       77,   77,   62,   36,   36,   10,   10,   39,   10,   40,
       61,   62,  118,   39,  118,   40,   10,   18,   18,   18,
       18,   79,   18,   18,   18,   18,   18,   18,  231,   18,
       50,   51,   39,   40,   39,   50,   51,   65,   40,   79,
       39,   51,   51,   84,   84,   66,   18,   18,   18,   18,
       18,   18,   18,   66,   41,   88,   65,   42,   89,   89,
       41,   88,  230,   42,   89,   18,   22,   22,   22,  229,

       22,   22,   22,   22,   22,   22,   41,   22,   41,   42,
      117,  117,   22,   42,   90,   43,   42,   42,  111,   41,
       90,   43,  249,  111,   22,   22,   22,   22,   22,   22,
       22,   23,   23,   23,  241,   23,   23,   23,   23,   23,
       23,  249,   23,   23,   43,   78,   78,   78,   81,   81,
       81,   81,   95,  119,  241,  119,   43,  228,   95,   23,
       23,   23,   23,   23,   23,   23,   37,   37,  144,   37,
      227,  101,  144,   52,   52,   37,   52,  101,   78,   37,
       37,   52,   37,   37,   37,   52,   52,   97,   52,   52,
       52,   98,  124,   97,   98,   97,  100,   98,  100,  126,

      131,  134,  124,  226,  100,  137,  131,  134,  135,  126,
      138,  137,  149,  149,  135,  150,  138,  150,  151,  156,
      151,  157,  182,  182,  131,  131,  224,  137,  156,  223,
      157,  222,  134,  184,  138,  135,  180,  180,  180,  184,
      185,  189,  191,  192,  197,  220,  185,  189,  191,  192,
      218,  225,  209,  207,  197,  205,  203,  195,  193,  188,
      225,  179,  178,  177,  197,  176,  175,  174,  173,  180,
      225,  253,  253,  253,  253,  254,  254,  254,  254,  255,
      255,  256,  172,  256,  256,  257,  257,  257,  257,  171,
      167,  161,  160,  159,  158,  155,  154,  153,  152,  148,

      147,  146,  145,  143,  142,  141,  140,  139,  136,  133,
      132,  130,  129,  128,  127,  123,  122,  121,  120,  116,
      115,  114,  112,  110,  108,  106,  105,  103,   99,   96,
       93,   76,   75,   74,   73,   72,   71,   70,   69,   67,
       64,   59,   53,   48,   47,   45,   38,   33,   32,   30,
       12,    9,    5,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "src/assembler/gblexer.l"
#line 2 "src/assembler/gblexer.l"
	#include "gbparser.hpp"
  #include "gblexer.h"
  #include "assembler.h"
  #include "../opcodes.h"
  #include "../utils.h"
  #include <string>
  
  typedef assembler::Parser::token token;
  
  #define yyterminate() assembler::Parser::make_END(loc);
  
  
  //
  
  static std::string buffer;
  static assembler::location loc;
  using namespace assembler;
#line 638 "src/assembler/gblexer.cpp"

#line 30 "src/assembler/gblexer.l"
  # define YY_USER_ACTION  loc.columns((int)yyleng);
#line 642 "src/assembler/gblexer.cpp"
#line 643 "src/assembler/gblexer.cpp"

#define INITIAL 0
#define sstring 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 34 "src/assembler/gblexer.l"



#line 38 "src/assembler/gblexer.l"
  loc.step();


#line 784 "src/assembler/gblexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 253 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 454 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "src/assembler/gblexer.l"
{ return Parser::make_T_COLON(loc); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 42 "src/assembler/gblexer.l"
{ return Parser::make_T_COMMA(loc); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "src/assembler/gblexer.l"
{ return Parser::make_T_QUOTE(loc); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 45 "src/assembler/gblexer.l"
{ return Parser::make_OP_NOP(loc); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 46 "src/assembler/gblexer.l"
{ return Parser::make_OP_HALT(loc); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 47 "src/assembler/gblexer.l"
{ return Parser::make_OP_STOP(loc); } // GB
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "src/assembler/gblexer.l"
{ return Parser::make_OP_LD(loc); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "src/assembler/gblexer.l"
{ return Parser::make_OP_LDI(loc); } // GB
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 51 "src/assembler/gblexer.l"
{ return Parser::make_OP_LDD(loc); } // GB
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 53 "src/assembler/gblexer.l"
{ return Parser::make_OP_ADD(loc); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 54 "src/assembler/gblexer.l"
{ return Parser::make_OP_ADC(loc); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 55 "src/assembler/gblexer.l"
{ return Parser::make_OP_SUB(loc); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 "src/assembler/gblexer.l"
{ return Parser::make_OP_SBC(loc); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 57 "src/assembler/gblexer.l"
{ return Parser::make_OP_DAA(loc); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 59 "src/assembler/gblexer.l"
{ return Parser::make_OP_AND(loc); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 60 "src/assembler/gblexer.l"
{ return Parser::make_OP_XOR(loc); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 61 "src/assembler/gblexer.l"
{ return Parser::make_OP_OR(loc); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 62 "src/assembler/gblexer.l"
{ return Parser::make_OP_CP(loc); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 64 "src/assembler/gblexer.l"
{ return Parser::make_OP_INC(loc); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 65 "src/assembler/gblexer.l"
{ return Parser::make_OP_DEC(loc); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 67 "src/assembler/gblexer.l"
{ return Parser::make_OP_CPL(loc); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 68 "src/assembler/gblexer.l"
{ return Parser::make_OP_SCF(loc); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 69 "src/assembler/gblexer.l"
{ return Parser::make_OP_CCF(loc); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 71 "src/assembler/gblexer.l"
{ return Parser::make_CC_COND(COND_NZ,loc); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 72 "src/assembler/gblexer.l"
{ return Parser::make_CC_COND(COND_Z,loc); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 73 "src/assembler/gblexer.l"
{ return Parser::make_CC_COND(COND_NC,loc); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 74 "src/assembler/gblexer.l"
{ return Parser::make_CC_COND(COND_C,loc); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 75 "src/assembler/gblexer.l"
{ return Parser::make_CC_COND(COND_PO,loc); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 76 "src/assembler/gblexer.l"
{ return Parser::make_CC_COND(COND_PE,loc); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 77 "src/assembler/gblexer.l"
{ return Parser::make_CC_COND(COND_SP,loc); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 78 "src/assembler/gblexer.l"
{ return Parser::make_CC_COND(COND_SN,loc); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 81 "src/assembler/gblexer.l"
{ return Parser::make_OP_JR(loc); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 82 "src/assembler/gblexer.l"
{ return Parser::make_OP_JRNZ(loc); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 83 "src/assembler/gblexer.l"
{ return Parser::make_OP_JRZ(loc); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 84 "src/assembler/gblexer.l"
{ return Parser::make_OP_JRNC(loc); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 85 "src/assembler/gblexer.l"
{ return Parser::make_OP_JRC(loc); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 86 "src/assembler/gblexer.l"
{ return Parser::make_OP_DJNZ(loc); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 88 "src/assembler/gblexer.l"
{ return Parser::make_OP_JP(loc); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 89 "src/assembler/gblexer.l"
{ return Parser::make_OP_CALL(loc); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 90 "src/assembler/gblexer.l"
{ return Parser::make_OP_RST(loc); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 91 "src/assembler/gblexer.l"
{ return Parser::make_OP_RET(loc); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 92 "src/assembler/gblexer.l"
{ return Parser::make_OP_RETI(loc); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 93 "src/assembler/gblexer.l"
{ return Parser::make_OP_PUSH(loc); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 94 "src/assembler/gblexer.l"
{ return Parser::make_OP_POP(loc); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 96 "src/assembler/gblexer.l"
{ return Parser::make_OP_BIT(loc); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 97 "src/assembler/gblexer.l"
{ return Parser::make_OP_RES(loc); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 98 "src/assembler/gblexer.l"
{ return Parser::make_OP_SET(loc); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 100 "src/assembler/gblexer.l"
{ return Parser::make_OP_RLCA(loc); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 101 "src/assembler/gblexer.l"
{ return Parser::make_OP_RLA(loc); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 102 "src/assembler/gblexer.l"
{ return Parser::make_OP_RRCA(loc); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 103 "src/assembler/gblexer.l"
{ return Parser::make_OP_RRA(loc); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 105 "src/assembler/gblexer.l"
{ return Parser::make_OP_RLC(loc); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 106 "src/assembler/gblexer.l"
{ return Parser::make_OP_RL(loc); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 107 "src/assembler/gblexer.l"
{ return Parser::make_OP_RRC(loc); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 108 "src/assembler/gblexer.l"
{ return Parser::make_OP_RR(loc); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 109 "src/assembler/gblexer.l"
{ return Parser::make_OP_SLA(loc); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 110 "src/assembler/gblexer.l"
{ return Parser::make_OP_SRA(loc); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 111 "src/assembler/gblexer.l"
{ return Parser::make_OP_SLL(loc); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 112 "src/assembler/gblexer.l"
{ return Parser::make_OP_SRL(loc); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 113 "src/assembler/gblexer.l"
{ return Parser::make_OP_SWAP(loc); } // GB
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 115 "src/assembler/gblexer.l"
{ return Parser::make_OP_EI(loc); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 116 "src/assembler/gblexer.l"
{ return Parser::make_OP_DI(loc); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 119 "src/assembler/gblexer.l"
{ return Parser::make_OP_OUT(loc); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 120 "src/assembler/gblexer.l"
{ return Parser::make_OP_IN(loc); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 122 "src/assembler/gblexer.l"
{ return Parser::make_OP_EX(loc); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 123 "src/assembler/gblexer.l"
{ return Parser::make_OP_EXX(loc); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 125 "src/assembler/gblexer.l"
{ return Parser::make_RDP_BC(loc); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 126 "src/assembler/gblexer.l"
{ return Parser::make_RDP_DE(loc); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 127 "src/assembler/gblexer.l"
{ return Parser::make_RDP_SP(loc); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 129 "src/assembler/gblexer.l"
{ return Parser::make_RD_BC(0, loc); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 130 "src/assembler/gblexer.l"
{ return Parser::make_RD_DE(1, loc); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 131 "src/assembler/gblexer.l"
{ return Parser::make_RD_HL(2, loc); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 132 "src/assembler/gblexer.l"
{ return Parser::make_RD_SP(3, loc); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 133 "src/assembler/gblexer.l"
{ return Parser::make_RD_AF(3, loc); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 135 "src/assembler/gblexer.l"
{ return Parser::make_RS_B(0, loc); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 136 "src/assembler/gblexer.l"
{ return Parser::make_RS_C(1, loc); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 137 "src/assembler/gblexer.l"
{ return Parser::make_RS_D(2, loc); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 138 "src/assembler/gblexer.l"
{ return Parser::make_RS_E(3, loc); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 139 "src/assembler/gblexer.l"
{ return Parser::make_RS_H(4, loc); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 140 "src/assembler/gblexer.l"
{ return Parser::make_RS_L(5, loc); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 141 "src/assembler/gblexer.l"
{ return Parser::make_RS_HL(6, loc); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 142 "src/assembler/gblexer.l"
{ return Parser::make_RS_A(7, loc); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 144 "src/assembler/gblexer.l"
{ return Parser::make_T_LPAREN(loc); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 145 "src/assembler/gblexer.l"
{ return Parser::make_T_RPAREN(loc); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 147 "src/assembler/gblexer.l"
{ return Parser::make_U16(strtol( &yytext[2], NULL, 16), loc); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 148 "src/assembler/gblexer.l"
{ return Parser::make_U16(strtol( yytext, NULL, 16), loc); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 149 "src/assembler/gblexer.l"
{ return Parser::make_U16(strtol( yytext, NULL, 16), loc); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 150 "src/assembler/gblexer.l"
{ return Parser::make_U16(strtol( &yytext[2], NULL, 2), loc); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 151 "src/assembler/gblexer.l"
{ return Parser::make_U16(strtol( yytext, NULL, 2), loc); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 152 "src/assembler/gblexer.l"
{ return Parser::make_U16(strtol( yytext, NULL, 2), loc); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 153 "src/assembler/gblexer.l"
{ return Parser::make_U16(atoi(yytext), loc);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 155 "src/assembler/gblexer.l"
{ return Parser::make_FLOAT(atof(yytext), loc); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 157 "src/assembler/gblexer.l"
{ buffer.clear(); BEGIN(sstring); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 159 "src/assembler/gblexer.l"
{ BEGIN(INITIAL); return Parser::make_LITERAL(buffer.c_str(), loc); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 160 "src/assembler/gblexer.l"
{ buffer += '\n'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 161 "src/assembler/gblexer.l"
{ buffer += '\0'; }
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 162 "src/assembler/gblexer.l"
{ buffer += yytext[1]; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 163 "src/assembler/gblexer.l"
{ char *ptr = yytext; while (*ptr) buffer += *ptr++; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 164 "src/assembler/gblexer.l"
{ return Parser::make_IDENTIFIER(yytext,loc); }
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 166 "src/assembler/gblexer.l"
{ loc.lines(1); return Parser::make_EOL(loc); }
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 169 "src/assembler/gblexer.l"
{ loc.lines((int)yyleng); return Parser::make_EOL(loc); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 170 "src/assembler/gblexer.l"
{ /* ignore whitespace */ }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 171 "src/assembler/gblexer.l"
{ assembler.error(loc, "Unrecognized character."); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(sstring):
#line 173 "src/assembler/gblexer.l"
{ return yyterminate(); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 176 "src/assembler/gblexer.l"
ECHO;
	YY_BREAK
#line 1369 "src/assembler/gblexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 253 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 253 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 252);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 176 "src/assembler/gblexer.l"



